// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PyRZyBot_2._0.Entities;

namespace PyRZyBot_2._0.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20210308165430_added_Question_Spam_Collumn")]
    partial class added_Question_Spam_Collumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PyRZyBot_2._0.Entities.ChannelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChannelInfo");
                });

            modelBuilder.Entity("PyRZyBot_2._0.Entities.ChatUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GotOnline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<int>("MessagesSent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionSpam")
                        .HasColumnType("int");

                    b.Property<int>("TwitchId")
                        .HasColumnType("int");

                    b.Property<int>("Watchtime")
                        .HasColumnType("int");

                    b.Property<int>("tldr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId");

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("PyRZyBot_2._0.Entities.ChatUsers_S", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AcceptsDuels")
                        .HasColumnType("bit");

                    b.Property<int>("DuelId")
                        .HasColumnType("int");

                    b.Property<int>("DuelsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("DuelsWon")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("MaxDuelBet")
                        .HasColumnType("int");

                    b.Property<int>("MaxLoseStreak")
                        .HasColumnType("int");

                    b.Property<int>("MaxWinStreak")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<int>("TwitchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatUsers_S");
                });

            modelBuilder.Entity("PyRZyBot_2._0.Entities.ChatUsers", b =>
                {
                    b.HasOne("PyRZyBot_2._0.Entities.ChatUsers_S", "ChatUsers_S")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .HasPrincipalKey("TwitchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatUsers_S");
                });
#pragma warning restore 612, 618
        }
    }
}
